#markdown: kramdown
#permalink: "pretty"

#title: "GLUG-PESCE"

#defaults:
#    scope:
#      path: ""
#      type: posts
#    values:
#      layout: post
#      permalink: /:categories/:title/
   url: glugpesce.github.io
   baseurl: /GLUG-PESCE
